---
apiVersion: v1
kind: Secret
metadata:
  name: mysecretgp
  # namespace: <nome-aluno>
type: Opaque
data:
  username: Z2FicmllbHBlcnJvbmk=
  password: cG9hcG9hMDkwOQ==

---
apiVersion: v1
kind: Pod
metadata:
  name: mypodsecret
  # namespace: <nome-aluno>
spec:
  containers:
  - name: mypodsecret
    image: redis
    env:
    - name: username
      valueFrom:
        secretKeyRef:
          name: mysecretgp
          key: username
    - name: password
      valueFrom:
        secretKeyRef:
          name: mysecretgp
          key: password

